name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: self-hosted

    steps:
      - uses: tgymnich/fork-sync@v2.0.10
        with:
          owner: Tampa/opensim
          base: master
          head: master
