name: .msbuildnet6

on:
  push:
    branches: [ "master" ]
    paths:
      - '**.cs'
  workflow_dispatch:

jobs:
  build:

    if: github.repository == 'Tampa/opensim'
    runs-on: [self-hosted, windows-server]
    steps:
    - uses: actions/checkout@v4
    - name: shortsha
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"   
    - name: preBuild
      run: bash ${GITHUB_WORKSPACE}/runprebuild.sh

    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Build
      id: build
      run: dotnet build --configuration Release OpenSim.sln

    - name: release
      if: success()
      run: zip -r LastDotNetBuild.zip bin ThirdPartyLicenses README.md CONTRIBUTORS.txt LICENSE.txt 
    - uses: softprops/action-gh-release@v1
      if: success()
      with:
          tag_name: r${{ steps.vars.outputs.sha_short }}
          name: LastDotNetAutoBuild
          files: LastDotNetBuild.zip