name: .msbuildnet6

on:
  push:
    branches: [ "master" ]
    paths:
      - '**.cs'
  workflow_dispatch:

jobs:
  build:

    if: ${{ github.repository == 'Tampa/opensim' }}
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: shortsha
      id: vars
      shell: bash
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

    - name: preBuild
      run: runprebuild.bat
      shell: cmd

    - name: Build
      id: build
      run: dotnet build --configuration Release OpenSim.sln

    - name: ScriptSyntaxUpdate
      run: |
        python $env:GITHUB_WORKSPACE\share\GenScriptSyntax\GenScriptSyntax.py $env:GITHUB_WORKSPACE $env:GITHUB_WORKSPACE\bin

    - name: release
      if: success()
      run: powershell -Command "Compress-Archive -Path bin, ThirdPartyLicenses, README.md, CONTRIBUTORS.txt, LICENSE.txt -DestinationPath LastDotNetBuild.zip"

    - uses: softprops/action-gh-release@v1
      if: success()
      with:
        tag_name: r${{ steps.vars.outputs.sha_short }}
        name: LastDotNetAutoBuild
        files: LastDotNetBuild.zip
